# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtok" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "e395041ba1ac14a9ed13f4780c199a29ff77bcb7d8e8e429e1f98958674ecbb3"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65530d6175e2782f9a5b131f0443ed35812bdcde1899d955ec7c0e682f87d2ab"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "740a0e24fa575222f979a686987ac7f7b0390c9a66165c0bbdafa48ae639c294"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3dbf77bbbda20651dd361866d66d27ab18b972f99a9079668f5119a53aafca15"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mtok"
  desc "Terminal dashboard for AI token usage and spend from local Claude Code and Codex logs"
  homepage "https://github.com/kerem-kaynak/mtok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mtok"]
    end
  end

  # No zap stanza required

end
