# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtok" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "b3f3f08b8e5dcc511fba1ed1808f1323cd963067177227654c4466eaf2f3064e"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3aba76732555a427095496ba480fb4b08212a1c10951c8375d358f680593880c"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6c342b170be9bb511ad8e9b91049890c2b94e2dae86b482054c0c633b37e3c9"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45b10f043b5e4485d3ca3558c9901c1361e247c5163910ec7af23e93c6d2ce45"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mtok"
  desc "Terminal dashboard for AI token usage and spend from local Claude Code and Codex logs"
  homepage "https://github.com/kerem-kaynak/mtok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mtok"]
    end
  end

  # No zap stanza required

end
