# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtok" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "97384604b7d61ac64959875cb98076ee588a12c7ccd0dc8c4d5ae5164650e40f"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ff59b662c503e0bc1772d94812ed38f91552cf37ce39ffe2697412c8189317e"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33046be9280df185ce8acf697dec849167e7b25209bb9b59eb731721806f346b"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "166508b87a5e76a6b3dc120c2fdd3b07c5441d9e0065582f6a671388dfbb3418"
      url "https://github.com/kerem-kaynak/mtok/releases/download/v#{version}/mtok_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mtok"
  desc "Terminal dashboard for AI token usage and spend from local Claude Code and Codex logs"
  homepage "https://github.com/kerem-kaynak/mtok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtok"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mtok"]
    end
  end

  # No zap stanza required

end
